### ISSUE TITLE
Sun misaligned to the edge of the webpage.

### ISSUE THREAD

**Issue by Full-Life-Alyx** [chostudio/BirbHunt#6]
![image](https://user-images.githubusercontent.com/96643025/194826101-5354042a-47d3-4241-b4cd-aa5e69b4b72f.png)
As you can see here, the sun goes all goofy and stuff, this could be because I have a wider monitor or it could be universal.

The current css at this time:
`background-position: 0px 15px, 257px 0px, 0px 0px;`
I think the sun should use something relative to the left side of the webpage.

**Comment by chostudio** [comment]
I fixed it
